sudo: required
language: python
python:
    - "3.7-dev"
addons:
  postgresql: "9.4"

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "create database iot;" -U postgres

script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
    - coverage run --source='.' manage.py test
    - coverage report

after_success:
    - coveralls 
